### PR TITLE
Define "Assumed Name"

### PR DESCRIPTION
**Pull request by RufusJWB**
As the concept of "Assumed Name" or "DBA" is not widely known outside of the USA we should clarify its meaning. The proposed definition comes from https://en.wikipedia.org/wiki/Trade_name .

### CODE REVIEW

**Comment by CBonnell** [comment]
Is there any instance in the SMBRs where "Assumed Name" (title case) is used?

**Comment by XolphinMartijn** [comment]
> Is there any instance in the SMBRs where "Assumed Name" (title case) is used?

There is not, but there are a number of occurrences where it would apply in case we do add it as a definition. 
If we want to make it a defined term, then lets also update the text to start using it.

I'm not a fan of " do not operate under their registered company name" though. One company could use their registered name for one business purpose, and another (DBA/Assumed Name) for other purposes. I think the clarification given in 3.2.3.2.2 is more to the point (and already included):

"...assumed name (also known as "doing business as", "DBA", or "d/b/a" name in the US and "trading as" name in the UK) to be included in the Certificate"

Seems like that's kind of a definition that's not listed in the definitions.

**Comment by RufusJWB** [comment]
> Is there any instance in the SMBRs where "Assumed Name" (title case) is used?

As soon as we have the definition, I'd update all instances with lower case to have capital cases.

**Comment by RufusJWB** [comment]
> Seems like that's kind of a definition that's not listed in the definitions.

We might move that definition from chapter 3.2.3.2.2 to the definitions section.

**Comment by CBonnell** [comment]
> > Is there any instance in the SMBRs where "Assumed Name" (title case) is used?
> 
> As soon as we have the definition, I'd update all instances with lower case to have capital cases.

I agree that would be a useful improvement. Initially this PR looked like a Defined Term was being defined without it actually being used anywhere, but if we introduce that term in the text it should add clarity.

**Comment by srdavidson** [comment]
Have implemented as https://github.com/cabforum/smime/pull/174

**Pull request closed without merging**
