### PR TITLE
Logging of signatures of OCSP responses removed

### PR DESCRIPTION
**Pull request by RufusJWB**
I don't believe it is reasonable to log every event, when the OCSP responder signs an OCSP response.

### CODE REVIEW

**Comment by CBonnell** [comment]
The intent of the requirement to log all of Certificate, CRL, and OCSP signing is so that all uses of the CA Private Key are logged so that in the event where such records are required for analysis, there will be a complete accounting of all signing operations. Omitting OCSP signing from this requirement will mean that there is a gap in such logging records.

**Comment by RufusJWB** [comment]
Would this mean, that if an OCSP response is signed by the private key belonging to an OCSP responder certificate and not by the CA certificate itself, we don't have to log it? And the same would be true for a delegated CRL signer?

**Comment by CBonnell** [comment]
> Would this mean, that if an OCSP response is signed by the private key belonging to an OCSP responder certificate and not by the CA certificate itself, we don't have to log it? And the same would be true for a delegated CRL signer?

I imagine having logging information for the delegated signing of OCSP responses or other revocation service artifacts would be similarly as useful as it would be for direct signing.

Can you share your rationale for the proposed change?

**Comment by RufusJWB** [comment]
> Can you share your rationale for the proposed change?

Even our OCSP responder signs tens of thousands OCSP responses every day. I assume big CAs are signing millions of them per day. So, I don't think it is of any use to store all this information for an extended period. Of course, I'd expect that the information about the signing of the OCSP responder certificate to be archived.

**Comment by srdavidson** [comment]
This may be reconsidered later as part of overall consideration of revocation services.

**Comment by RufusJWB** [comment]
> This may be reconsidered later as part of overall consideration of revocation services.

I'm sorry, but I'd like to clarify this further. Is it the expectation of the SBR that a compliant CA shall store for two years (chapter 5.4.3) information including date and time as well as a description (chapter 5.4.1, very end) about each single OCSP responder response (chapter 5.4.1, paragraph 2, point VI) created by the CA?

**Pull request closed without merging**
